name: Parallel Quick Sort

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'coretto'
        cache: gradle
    
    - name: Run Build
      uses: ./gradlew build -x test
    
    - name: Run Test
      run: ./gradlew test
      
    - name: Run JMH Benchmark
      run: ./gradlew jmh
